version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - weaviate
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=shl24
      - DATABASE_USER=shl24
      - DATABASE_PASSWORD=shl24
      - BRAVE_SEARCH_API_KEY=${BRAVE_SEARCH_API_KEY}
      - YANDEX_API_KEY=${YANDEX_API_KEY}
      - YANDEX_FOLDER_ID=${YANDEX_FOLDER_ID}
      - WEAVIATE_HOST=weaviate
      - WEAVIATE_PORT=8080
      - LOG_LEVEL=DEBUG
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - app-network

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=shl24
      - POSTGRES_PASSWORD=shl24
      - POSTGRES_DB=shl24
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  weaviate:
    image: semitechnologies/weaviate:1.30.4
    environment:
      - QUERY_DEFAULTS_LIMIT=25
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - DEFAULT_VECTORIZER_MODULE=none
      - CLUSTER_HOSTNAME=node1
    volumes:
      - weaviate_data:/var/lib/weaviate
    networks:
      - app-network

volumes:
  postgres_data:
  weaviate_data:

networks:
  app-network:
    driver: bridge
